### ISSUE TITLE
TypeError: head.removeHeadObjs is not a function

### ISSUE THREAD

**Issue by michealroberts** [vueuse/schema-org#31]
Not sure what to add other than the stack trace, but moving between routes in app seems to throw this error:

```
vueuse-head.plugin.mjs?t=1668271525765&v=132df26e:41 Uncaught (in promise) TypeError: head.removeHeadObjs is not a function
    at vueuse-head.plugin.mjs?t=1668271525765&v=132df26e:41:12
    at runtime-core.esm-bundler.js:2739:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:21)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2713:29)
    at invokeArrayFns (shared.esm-bundler.js:552:13)
    at unmountComponent (runtime-core.esm-bundler.js:6203:13)
    at unmount (runtime-core.esm-bundler.js:6097:13)
    at unmountComponent (runtime-core.esm-bundler.js:6212:13)
    at unmount (runtime-core.esm-bundler.js:6097:13)
```

Caveat - I'm using the Nuxt 3 module.

**Comment by harlan-zw** [comment]
Seems to be fixed, try deleting node_modules / lock file and re-install if not.
