### ISSUE TITLE
Cannot start nuxt:  Nuxt module should be a function: [object Object]

### ISSUE THREAD

**Issue by koronowicz** [vueuse/schema-org#38]
Hello, 

thanks for great work!

I've installed version 2.0 and getting this error when running dev server:

```
 ERROR  Cannot start nuxt:  Nuxt module should be a function: [object Object]    15:06:23

  at normalizeModule (node_modules/@nuxt/kit/dist/index.mjs:439:11)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:415:47)
  at initNuxt (node_modules/nuxt/dist/index.mjs:1825:13)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
```

My package.json 

```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "nuxt": "3.0.0",
    "sass": "^1.53.0",
    "@nuxt/content": "^2.2.2"
  },
  "dependencies": {
    "@funken-studio/sitemap-nuxt-3": "^4.0.4",
    "@vueuse/schema-org": "^2.0.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "vue-gtag-next": "^1.14.0",
    "vue3-click-away": "^1.2.4"
  }
}
```

Can't figure out where the problem is.

**Comment by koronowicz** [comment]
Thank you, it's working now!
